name = "RPM Spec"
grammar = "rpmspec"
path_suffixes = ["spec"]
line_comments = ["# "]
tab_size = 4
hard_tabs = false

brackets = [
  { start = "%{", end = "}", close = true, newline = false },
  { start = "%(", end = ")", close = true, newline = false },
  { start = "${", end = "}", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
]
